In [1]:
import requests
from dotenv import load_dotenv
import os

In [8]:
load_dotenv(override=True)  # <-- override=True força sobrescrever variáveis já carregadas
TOKEN = os.getenv("TOKEN")
print(f"Token carregado: {TOKEN[:10]}...")  # confirme que é o token novo
resposta = requests.get(
    "https://data.fantastic.jobs/v1/active-jb",
    headers={
        "Authorization": f"Bearer {TOKEN}"
    },
    params={
      "time_frame": "24h"
    }
)

print(resposta.status_code)
print(resposta.text)

Token carregado: zpka_14599...
200
[{"id":2227914099,"date_posted":"2026-06-26T21:58:56.929","date_created":"2026-06-26T21:58:57.056961","title":"Representant Commercial Secteur Bretagne et Normandie","organization":"Roto la Fenêtre de Toit","organization_url":"https://www.linkedin.com/company/roto-la-fen%C3%AAtre-de-toit","date_valid_through":null,"locations":[{"@type":"Place","address":{"@type":"PostalAddress","addressRegion":"","addressCountry":"","addressLocality":"France"}}],"location_type":null,"location_requirements":null,"salary":null,"employment_type":null,"url":"https://fr.linkedin.com/jobs/view/representant-commercial-secteur-bretagne-et-normandie-at-roto-la-fen%C3%AAtre-de-toit-4433318807","source_type":"jobboard","source":"linkedin","source_domain":"fr.linkedin.com","organization_logo":"https://media.licdn.com/dms/image/v2/C4E0BAQHUnx8gDCtNFA/company-logo_100_100/company-logo_100_100/0/1669106579349/roto_la_fentre_de_toit_logo?e=2147483647&v=beta&t=s53cVyH8VwnCMid1AfB9-XYbxQl-tHB_IWRp98VNvAM","cities_derived":null,"counties_derived":null,"regions_derived":null,"countries_derived":["France"],"locations_derived":["France"],"timezones_derived":["Europe/Paris"],"lats_derived":[46.603354],"lngs_derived":[1.8883335],"seniority":"Premier emploi","direct_apply":true,"no_jb_schema":true,"ats_duplicate":null,"linkedin_id":4433318807,"org_linkedin_slug":"roto-la-fen%C3%AAtre-de-toit","org_linkedin_headcount":9,"org_linkedin_website":"https://www.roto-fenetres-de-toit.fr","org_linkedin_size":"5,001-10,000 employees","org_linkedin_slogan":"Marque et fabricant leader de fenêtres de toit de qualité supérieure depuis 1935.","org_linkedin_industry":"Wholesale Building Materials","org_linkedin_followers":1503,"org_linkedin_headquarters":"Saint Avold, Moselle","org_linkedin_type":"Privately Held","org_linkedin_founded_date":"1935","org_linkedin_specialties":["Bâtiment","Fabricant de Fenêtres de toit","PVC","Etanchéité","and Maison de rêve"],"org_linkedin_locations":["40 C Rue Altmayer, Saint Avold, Moselle 57500, FR"],"org_linkedin_description":"Marque et fabricant leader de fenêtres de toit de qualité supérieure depuis 1935. \nRoto facilite votre travail grâce à des produits sophistiqués, tout type de fenêtres de toit en bois ou PVC / volets et stores intérieurs / extérieurs, simple à installer et vous aide à répondre à toutes les demandes de vos clients exigeants partout en France.","org_linkedin_recruitment_agency_derived":false,"recruiter_name":"JEREMY CARON","recruiter_title":"Directeur Général France\n\n“ Energy and Passion are the basis of Life”","recruiter_url":"https://fr.linkedin.com/in/jeremy-caron-2095256a","ai_salary_currency":null,"ai_salary_value":null,"ai_salary_min_value":null,"ai_salary_max_value":null,"ai_salary_unit_text":null,"ai_benefits":null,"ai_experience_level":"2-5","ai_work_arrangement":"On-site","ai_work_arrangement_office_days":null,"ai_remote_location":null,"ai_remote_location_derived":null,"ai_key_skills":["Sales","Negotiation","Customer Service","Communication","Active Listening","Analytical Skills","Training","Building Relationships","Autonomy","Digital Tools","CRM","Office Suite","Construction Knowledge","Roofing","Closure","Zinc Work"],"ai_hiring_manager_name":null,"ai_hiring_manager_email_address":null,"ai_core_responsibilities":"As a Sales Representative, you will promote and sell roof windows and accessories to professional clients. Your daily tasks include prospecting new clients, maintaining and developing the existing portfolio, and conducting site visits to present products and identify needs.","ai_requirements_summary":"Candidates should have confirmed sales experience in roofing, closure, or zinc work, along with strong negotiation skills and the ability to develop a client portfolio in a B2B environment. Excellent communication skills, active listening, and a customer service mindset are essential for building lasting relationships.","ai_working_hours":40,"ai_employment_type":["FULL_TIME"],"ai_job_language":"French","ai_visa_sponsorship":false,"ai_keywords":["Roof Windows","Accessories","Sales","B2B","Prospecting","Client Portfolio","Site Visits","Demonstrations","Product Training","Construction","Zinc Work","Communication","Customer Service","Digital Tools","CRM","Office Suite"],"ai_taxonomies_a":["Sales","Construction","Trades"],"ai_education":null},
 {"id":2227909676,"date_posted":"2026-06-26T21:56:50.095","date_created":"2026-06-26T21:56:50.168136","title":"Car Specialist, Europe","organization":"Hagerty","organization_url":"https://www.linkedin.com/company/hagertycars","date_valid_through":null,"locations":[{"@type":"Place","address":{"@type":"PostalAddress","addressRegion":"","addressCountry":"","addressLocality":"France"}}],"location_type":null,"location_requirements":null,"salary":null,"employment_type":null,"url":"https://fr.linkedin.com/jobs/view/car-specialist-europe-at-hagerty-4395340259","source_type":"jobboard","source":"linkedin","source_domain":"fr.linkedin.com","organization_logo":"https://media.licdn.com/dms/image/v2/D560BAQETtkT5lhPEOg/company-logo_100_100/B56ZuAKSE3KgAQ-/0/1767381738318/hagertycars_logo?e=2147483647&v=beta&t=uUKVAGlQ1CJngPe0DZfsItd87aLGk1AccnOW4UW9zc8","cities_derived":null,"counties_derived":null,"regions_derived":null,"countries_derived":["France"],"locations_derived":["France"],"timezones_derived":["Europe/Paris"],"lats_derived":[46.603354],"lngs_derived":[1.8883335],"seniority":"Cadre","direct_apply":false,"no_jb_schema":true,"ats_duplicate":true,"linkedin_id":4395340259,"org_linkedin_slug":"hagertycars","org_linkedin_headcount":1692,"org_linkedin_website":"http://careers.hagerty.com","org_linkedin_size":"1,001-5,000 employees","org_linkedin_slogan":"We're Hagerty, and we help enthusiast drivers insure, buy/sell and enjoy their rides. #NeverStopDriving","org_linkedin_industry":"Insurance","org_linkedin_followers":48577,"org_linkedin_headquarters":"Traverse City, MI","org_linkedin_type":"Public Company","org_linkedin_founded_date":"1983","org_linkedin_specialties":["Collector Car Valuation","Collector Motorcycle Insurance","Motorsports Insurance","Collector Car Insurance","Classic Boat Insurance","International Coverage","Business Insurance","Private Client Services","Hagerty Magazine","Digital Articles","and Videos","Roadside Assistance","Car Auction Coverage","Car Hobby Support","Media","Events","Membership Programs","Impact","and Leadership"],"org_linkedin_locations":["121 Drivers Edge, Traverse City, MI 49684-4203, US","1010 Johnson Rd, Suite  #150, Golden, Colorado 80401, US","The Arch Barn, Alderton Road, Towcester, NN12 7TB, GB","555 Metro Pl N, Dublin, Ohio 43017, US","5 Via Renzo Dr, Richmond Hill, Ontario L4S, CA"],"org_linkedin_description":"We're Hagerty, and we help enthusiast drivers insure, buy/sell and enjoy their rides. #NeverStopDriving\n ","org_linkedin_recruitment_agency_derived":false,"recruiter_name":null,"recruiter_title":null,"recruiter_url":null,"ai_salary_currency":null,"ai_salary_value":null,"ai_salary_min_value":null,"ai_salary_max_value":null,"ai_salary_unit_text":null,"ai_benefits":null,"ai_experience_level":"5-10","ai_work_arrangement":"Remote OK","ai_work_arrangement_office_days":null,"ai_remote_location":["France","Germany","Italy"],"ai_remote_location_derived":["France","Germany","Italy"],"ai_key_skills":["Sales Experience","Collector Cars","Client Relationship Management","Automotive Sales","Communication Skills","Integrity","Team Orientation","Market Understanding","Valuation Dynamics","Manual Transmission Operation"],"ai_hiring_manager_name":null,"ai_hiring_manager_email_address":null,"ai_core_responsibilities":"As a Car Specialist, you will help clients buy and sell collector cars through auctions and private sales. You will develop relationships with car collectors and provide high-quality advice and expertise.","ai_requirements_summary":"Candidates should have proven sales experience in the collector car industry and specialized knowledge of collector cars. Strong communication skills and the ability to operate manual transmissions are also required.","ai_working_hours":40,"ai_employment_type":["FULL_TIME"],"ai_job_language":"English","ai_visa_sponsorship":false,"ai_keywords":["Collector Cars","Sales","Client Relationships","Automotive Events","Auction","Private Sales","Market Trends","Valuation","Photography","Cataloging","Expense Management","Driving Events","Automotive Journalism","Hagerty Drivers Club"],"ai_taxonomies_a":["Sales","Transportation","Customer Service & Support"],"ai_education":null},
 {"id":2227909312,"date_posted":"2026-06-26T21:56:37.589","date_created":"2026-06-26T21:56:37.664729","title":"Wood Defect Product Owner","organization":"Neural Grader","organization_url":"https://www.linkedin.com/company/neural-grader","date_valid_through":null,"locations":[{"@type":"Place","address":{"@type":"PostalAddress","addressRegion":"","addressCountry":"","addressLocality":"France"}}],"location_type":null,"location_requirements":null,"salary":null,"employment_type":null,"url":"https://fr.linkedin.com/jobs/view/wood-defect-product-owner-at-neural-grader-4408418082","source_type":"jobboard","source":"linkedin","source_domain":"fr.linkedin.com","organization_logo":"https://media.licdn.com/dms/image/v2/D4E0BAQEvp1WabWtx_g/company-logo_100_100/B4EZbIhOnbGQAU-/0/1747120876863/neural_grader_logo?e=2147483647&v=beta&t=jt6lpLtJdwmjG995AkjHcdKiEoZ2ufPQlF_THujeVNk","cities_derived":null,"counties_derived":null,"regions_derived":null,"countries_derived":["France"],"locations_derived":["France"],"timezones_derived":["Europe/Paris"],"lats_derived":[46.603354],"lngs_derived":[1.8883335],"seniority":"Directeur","direct_apply":true,"no_jb_schema":true,"ats_duplicate":null,"linkedin_id":4408418082,"org_linkedin_slug":"neural-grader","org_linkedin_headcount":21,"org_linkedin_website":"https://www.neuralgrader.com","org_linkedin_size":"2-10 employees","org_linkedin_slogan":"AI-powered Lumber Scanner and Optimiser","org_linkedin_industry":"Software Development","org_linkedin_followers":1450,"org_linkedin_headquarters":"Sectorul 1, Bucharest","org_linkedin_type":"Privately Held","org_linkedin_founded_date":"","org_linkedin_specialties":[""],"org_linkedin_locations":["Strada Sevastopol 24, Sectorul 1, Bucharest 010992, RO"],"org_linkedin_description":"Neural Grader brings the power of AI automation to sawmills, increasing yield, eliminating grading errors and maximising profits. With advanced defect detection and seamless integration into existing lines, you can process lumber faster, more accurately and at lower costs.","org_linkedin_recruitment_agency_derived":false,"recruiter_name":null,"recruiter_title":null,"recruiter_url":null,"ai_salary_currency":null,"ai_salary_value":null,"ai_salary_min_value":null,"ai_salary_max_value":null,"ai_salary_unit_text":null,"ai_benefits":null,"ai_experience_level":"2-5","ai_work_arrangement":"On-site","ai_work_arrangement_office_days":null,"ai_remote_location":null,"ai_remote_location_derived":null,"ai_key_skills":["Forestry","Wood Processing","Lumber Grading","Data Analysis","Model Evaluation","Customer Feedback","Communication","Attention to Detail"],"ai_hiring_manager_name":null,"ai_hiring_manager_email_address":null,"ai_core_responsibilities":"The core mission is to own and improve the full data to model to customer feedback loop for defect detection. This includes investigating customer failure cases, improving evaluation datasets, and working closely with technical teams.","ai_requirements_summary":"Candidates should have a strong background in forestry, wood engineering, or wood science, along with practical understanding of wood defects. Good communication skills and the ability to work with data and technical workflows are essential.","ai_working_hours":40,"ai_employment_type":["FULL_TIME"],"ai_job_language":"English","ai_visa_sponsorship":false,"ai_keywords":["AI","Automated Wood Defect Detection","Grading","Sawmill","Data","Model","Customer Feedback","Annotation","Machine Learning","Quality Loop","Production Conditions","Evaluation Datasets","Validation Logic"],"ai_taxonomies_a":["Technology","Engineering","Manufacturing","Environmental & Sustainability","Data & Analytics"],"ai_education":["bachelor degree"]},
 {"id":2227908740,"date_posted":"2026-06-26T21:56:24.041","date_created":"2026-06-26T21:56:24.109612","title":"Conseiller en gestion de patrimoine indépendant","organization":"LIERE PATRIMOINE","organization_url":"https://www.linkedin.com/company/liere-patrimoine","date_valid_through":null,"locations":[{"@type":"Place","address":{"@type":"PostalAddress","addressRegion":"","addressCountry":"","addressLocality":"France"}}],"location_type":null,"location_requirements":null,"salary":null,"employment_type":null,"url":"https://fr.linkedin.com/jobs/view/conseiller-en-gestion-de-patrimoine-ind%C3%A9pendant-at-liere-patrimoine-4434021029","source_type":"jobboard","source":"linkedin","source_domain":"fr.linkedin.com","organization_logo":"https://media.licdn.com/dms/image/v2/D4E0BAQF-ZG-0A7qm3w/company-logo_100_100/company-logo_100_100/0/1737393834019?e=2147483647&v=beta&t=frCuheNnUX4aXyS-VQqxoTKfnU-aVDknSDyBxQW5v3Q","cities_derived":null,"counties_derived":null,"regions_derived":null,"countries_derived":["France"],"locations_derived":["France"],"timezones_derived":["Europe/Paris"],"lats_derived":[46.603354],"lngs_derived":[1.8883335],"seniority":"Premier emploi","direct_apply":true,"no_jb_schema":true,"ats_duplicate":null,"linkedin_id":4434021029,"org_linkedin_slug":"liere-patrimoine","org_linkedin_headcount":1,"org_linkedin_website":"https://calendly.com/gestion-conseil-liere-patrimoine/rendez-vous","org_linkedin_size":"1 employee","org_linkedin_slogan":"Chaque projet mérite une solution sur mesure. Parlons du vôtre","org_linkedin_industry":"Investment Advice","org_linkedin_followers":null,"org_linkedin_headquarters":"","org_linkedin_type":"Self-Employed","org_linkedin_founded_date":"","org_linkedin_specialties":[""],"org_linkedin_locations":[],"org_linkedin_description":null,"org_linkedin_recruitment_agency_derived":false,"recruiter_name":"Kyliam Liere","recruiter_title":"Conseiller en gestion de patrimoine | J’accompagne particuliers & dirigeants à faire les bons choix pour investir, optimiser et préparer l’avenir…","recruiter_url":"https://fr.linkedin.com/in/kyliam-liere","ai_salary_currency":null,"ai_salary_value":null,"ai_salary_min_value":null,"ai_salary_max_value":null,"ai_salary_unit_text":null,"ai_benefits":null,"ai_experience_level":"0-2","ai_work_arrangement":"On-site","ai_work_arrangement_office_days":null,"ai_remote_location":null,"ai_remote_location_derived":null,"ai_key_skills":["Advisory","Client Relationship","Communication","Progression","Long-term Planning"],"ai_hiring_manager_name":null,"ai_hiring_manager_email_address":null,"ai_core_responsibilities":"The role involves building a solid activity in wealth management and client support. The objective is to develop skills and provide a structured framework for professional growth.","ai_requirements_summary":"Candidates should be ambitious, serious, and human-oriented, with a desire to create trust-based relationships. Experience in banking, insurance, real estate, commerce, or management is beneficial, but not mandatory.","ai_working_hours":40,"ai_employment_type":["FULL_TIME"],"ai_job_language":"French","ai_visa_sponsorship":false,"ai_keywords":["Wealth Management","Client Support","Financial Development","Advisory Services","Trust Building","Career Transition"],"ai_taxonomies_a":["Finance & Accounting","Consulting","Sales"],"ai_education":null},
 {"id":2227908749,"date_posted":"2026-06-26T21:56:23.995","date_created":"2026-06-26T21:56:24.309115","title":"Senior Platform Architect","organization":"Axelera AI","organization_url":"https://www.linkedin.com/company/axelera-ai","date_valid_through":null,"locations":[{"@type":"Place","address":{"@type":"PostalAddress","addressRegion":"","addressCountry":"","addressLocality":"France"}}],"location_type":null,"location_requirements":null,"salary":null,"employment_type":null,"url":"https://fr.linkedin.com/jobs/view/senior-platform-architect-at-axelera-ai-4434017965","source_type":"jobboard","source":"linkedin","source_domain":"fr.linkedin.com","organization_logo":"https://media.licdn.com/dms/image/v2/C4D0BAQG5JoNHmUt4aw/company-logo_100_100/company-logo_100_100/0/1631087254252/axelera_ai_logo?e=2147483647&v=beta&t=xgY6QSLXmeHkdZkosbvWIkoU7exIW_oEgE0rN8bUtIw","cities_derived":null,"counties_derived":null,"regions_derived":null,"countries_derived":["France"],"locations_derived":["France"],"timezones_derived":["Europe/Paris"],"lats_derived":[46.603354],"lngs_derived":[1.8883335],"seniority":"Cadre","direct_apply":false,"no_jb_schema":true,"ats_duplicate":true,"linkedin_id":4434017965,"org_linkedin_slug":"axelera-ai","org_linkedin_headcount":286,"org_linkedin_website":"https://axelera.ai","org_linkedin_size":"201-500 employees","org_linkedin_slogan":"Creating a powerful, efficient and competitive AI-native hardware & software platform for edge computing","org_linkedin_industry":"Semiconductor Manufacturing","org_linkedin_followers":38735,"org_linkedin_headquarters":"Eindhoven","org_linkedin_type":"Privately Held","org_linkedin_founded_date":"2021","org_linkedin_specialties":["Artificial Intelligence","Edge Computing","Computer Vision","Machine Learning","and Edge Software"],"org_linkedin_locations":["HTC5, High Tech Campus, Eindhoven, 5656 AE , NL"],"org_linkedin_description":"Axelera AI delivers an AI-native game-changing hardware and software platform to accelerate artificial intelligence.\n\nHeadquartered in the AI Innovation Center of the High Tech Campus in Eindhoven, Axelera AI has R&D offices in Belgium, Switzerland, UK and Italy and operations in 15 European countries . Its team of experts in AI software and hardware hail from top AI firms and Fortune 500 companies.","org_linkedin_recruitment_agency_derived":false,"recruiter_name":null,"recruiter_title":null,"recruiter_url":null,"ai_salary_currency":null,"ai_salary_value":null,"ai_salary_min_value":null,"ai_salary_max_value":null,"ai_salary_unit_text":null,"ai_benefits":["Pension Plan","Employee Insurances","Stock Options"],"ai_experience_level":"5-10","ai_work_arrangement":"Remote OK","ai_work_arrangement_office_days":null,"ai_remote_location":["Belgium","Italy","Netherlands","United Kingdom"],"ai_remote_location_derived":["Belgium","Italy","Netherlands","United Kingdom"],"ai_key_skills":["System Architecture","Platform Architecture","Scale-Up Systems","Scale-Out Systems","Distributed Workload Mapping","Interconnect Architecture","Ethernet","Optical Technologies","Problem-Solving","Collaboration","AI Accelerator Systems","HPC Systems","Data Center Deployment"],"ai_hiring_manager_name":null,"ai_hiring_manager_email_address":null,"ai_core_responsibilities":"Define the platform-level architecture for scale-up and scale-out systems, ensuring effective workload execution. Collaborate with various teams and engage with customers on architecture requirements.","ai_requirements_summary":"Significant experience in system or platform architecture is required, with a strong focus on scale-up and scale-out designs. Candidates should have a deep understanding of interconnect technologies and the ability to lead multidisciplinary teams.","ai_working_hours":40,"ai_employment_type":["FULL_TIME"],"ai_job_language":"English","ai_visa_sponsorship":false,"ai_keywords":["AI Platform","Architecture","Accelerators","System Topology","Host Integration","Memory Organization","Performance","Scalability","Operability","Reliability","Availability","Serviceability","CXL","PCIe","Workloads","Interconnect Infrastructure","Methodology","Best Practices"],"ai_taxonomies_a":["Technology","Engineering","Data & Analytics","Manufacturing","Science & Research"],"ai_education":["postgraduate degree"]},

In [9]:
import json

dados = resposta.json()  # converte a resposta para dict/list Python

caminho = "VagasDados_remotive_api.json"

# Verifica se a requisição foi bem-sucedida antes de continuar
if resposta.status_code != 200:
    print(f"Erro na requisição: {resposta.status_code}")
    print(resposta.json().get("detail", "Sem detalhes"))
else:
    dados = resposta.json()  # só converte se status for 200

    # Garante que dados é uma lista
    if isinstance(dados, dict):
        dados = dados.get("jobs", dados.get("data", []))  # ajuste a chave conforme a API

    # 1. Lê o que já existe
    if os.path.exists(caminho):
        with open(caminho, "r", encoding="utf-8") as f:
            dados_existentes = json.load(f)
    else:
        dados_existentes = []

    print(f"Vagas já salvas: {len(dados_existentes)}")

    # 2. Junta e remove duplicatas
    dados_combinados = dados_existentes + dados

    vistos = set()
    # ... resto do código
dados_unicos = []
for vaga in dados_combinados:
    if vaga['id'] not in vistos:
        vistos.add(vaga['id'])
        dados_unicos.append(vaga)

# 4. Salva tudo de novo
with open(caminho, "w", encoding="utf-8") as f:
    json.dump(dados_unicos, f, ensure_ascii=False, indent=2)

print(f"Total após atualização: {len(dados_unicos)}")

Vagas já salvas: 113
Total após atualização: 213

In [ ]:
import json

with open("VagasDados_remotive_api.json", "r", encoding="utf-8") as f:
    arquivo = json.load(f)  # ← load para LER
print(arquivo)

In [6]:
import pandas as pd

df = pd.DataFrame(arquivo)
print(list(df.columns))

['id', 'date_posted', 'date_created', 'title', 'organization', 'organization_url', 'date_valid_through', 'locations', 'location_type', 'location_requirements', 'salary', 'employment_type', 'url', 'source_type', 'source', 'source_domain', 'organization_logo', 'cities_derived', 'counties_derived', 'regions_derived', 'countries_derived', 'locations_derived', 'timezones_derived', 'lats_derived', 'lngs_derived', 'seniority', 'direct_apply', 'no_jb_schema', 'ats_duplicate', 'linkedin_id', 'org_linkedin_slug', 'org_linkedin_headcount', 'org_linkedin_website', 'org_linkedin_size', 'org_linkedin_slogan', 'org_linkedin_industry', 'org_linkedin_followers', 'org_linkedin_headquarters', 'org_linkedin_type', 'org_linkedin_founded_date', 'org_linkedin_specialties', 'org_linkedin_locations', 'org_linkedin_description', 'org_linkedin_recruitment_agency_derived', 'recruiter_name', 'recruiter_title', 'recruiter_url', 'ai_salary_currency', 'ai_salary_value', 'ai_salary_min_value', 'ai_salary_max_value', 'ai_salary_unit_text', 'ai_benefits', 'ai_experience_level', 'ai_work_arrangement', 'ai_work_arrangement_office_days', 'ai_remote_location', 'ai_remote_location_derived', 'ai_key_skills', 'ai_hiring_manager_name', 'ai_hiring_manager_email_address', 'ai_core_responsibilities', 'ai_requirements_summary', 'ai_working_hours', 'ai_employment_type', 'ai_job_language', 'ai_visa_sponsorship', 'ai_keywords', 'ai_taxonomies_a', 'ai_education']

In [8]:
colunas_selecionadas = ['id','date_posted','title','organization','locations','ai_employment_type','source_type','seniority','ai_salary_currency','ai_salary_value','ai_salary_min_value','ai_salary_max_value','ai_salary_unit_text','ai_key_skills','ai_taxonomies_a','ai_education']
df_col_selecionadas = df[colunas_selecionadas]
df_col_selecionadas.head(5)

,id,date_posted,title,organization,locations,ai_employment_type,source_type,seniority,ai_salary_currency,ai_salary_value,ai_salary_min_value,ai_salary_max_value,ai_salary_unit_text,ai_key_skills,ai_taxonomies_a,ai_education
0,2213012062,2026-06-18T17:59:31,Insulator,"Shambaugh & Son, L.P.","[{'@type': 'Place', 'address': {'@type': 'Post...",[FULL_TIME],jobboard,Entry level,NaN,NaN,NaN,NaN,NaN,"[Insulation Installation, Blueprint Reading, S...","[Trades, Construction, Manufacturing]",[high school]
1,2213011835,2026-06-18T17:57:04,Shipping and Receiving,Sika,"[{'@type': 'Place', 'address': {'@type': 'Post...",[FULL_TIME],jobboard,Entry level,NaN,NaN,NaN,NaN,NaN,"[Shipping, Receiving, Forklift Operation, Mate...","[Manufacturing, Logistics, Construction, Trans...",[high school]
2,2213012036,2026-06-18T17:56:15,Project Engineer I - Roadway,"CESO, INC.","[{'@type': 'Place', 'address': {'@type': 'Post...",[FULL_TIME],jobboard,Entry level,USD,NaN,68415.0,122252.0,YEAR,"[Civil Engineering, AutoCAD, Civil 3D, AutoTur...","[Engineering, Construction, Creative & Media]",[bachelor degree]
3,2213011911,2026-06-18T17:56:01,Account Manager-Solutions,Imagine,"[{'@type': 'Place', 'address': {'@type': 'Post...",[FULL_TIME],jobboard,Mid-Senior level,USD,NaN,64800.0,91000.0,YEAR,"[Account Management, Project Management, Commu...","[Sales, Management & Leadership, Creative & Me...","[bachelor degree, high school]"
4,2213011067,2026-06-18T17:54:57,Anti Tamper Systems/Hardware Engineer (26-206),Trace3,"[{'@type': 'Place', 'address': {'@type': 'Post...",[FULL_TIME],jobboard,Mid-Senior level,USD,NaN,120000.0,145000.0,YEAR,"[Anti-Tamper, Risk Management, System Security...","[Engineering, Technology, Government & Public ...","[bachelor degree, postgraduate degree]"

In [9]:
# separa as colunas que vieram com listas nos valores para serem tratadas nas celulas abaixo
colunas_com_lista = []

for col in df_col_selecionadas.columns:
    tipos = df_col_selecionadas[col].apply(type).unique()
    #print(f"{col}: {tipos}")
    if list in tipos:
        print(col)
        if col == 'locations':
        # Normaliza os dados, especificando o caminho até o que quer "abrir"
            tratamento_col = pd.json_normalize(
                arquivo,                        # sua lista de vagas
                record_path=[col],      # qual campo é uma lista para "explodir" em linhas
                meta=['id'],           # além de explodir o campo aninhado, eu quero manter essas colunas do nível principal (pai) junto, em cada linha resultante.
                errors='ignore'
            )
            tratamento_col['address.addressCountry']
            df_col_selecionadas.loc[:, 'locations'] = (tratamento_col['address.addressCountry'])
        else:
            # Normaliza os dados, especificando o caminho até o que quer "abrir"
            tratamento_col = pd.json_normalize(
                arquivo,                        # sua lista de vagas
                record_path=[col],      # qual campo é uma lista para "explodir" em linhas
                meta=['id'],           # além de explodir o campo aninhado, eu quero manter essas colunas do nível principal (pai) junto, em cada linha resultante.
                errors='ignore'
            )
            tratamento_col[0]
            df_col_selecionadas.loc[:, col] = (tratamento_col[0]) # ":" selecione todas as linhas da coluna "col" e substitua por "tratamento_col[0]"

locations
ai_employment_type
ai_key_skills
ai_taxonomies_a
ai_education

In [10]:
print(df_col_selecionadas.columns)
df_col_selecionadas['date_posted'].dtype

Index(['id', 'date_posted', 'title', 'organization', 'locations',
       'ai_employment_type', 'source_type', 'seniority', 'ai_salary_currency',
       'ai_salary_value', 'ai_salary_min_value', 'ai_salary_max_value',
       'ai_salary_unit_text', 'ai_key_skills', 'ai_taxonomies_a',
       'ai_education'],
      dtype='str')

In [11]:
# tratamento das colunas 
df_col_selecionadas['ai_salary_value'] = df_col_selecionadas['ai_salary_value'].round(2)
df_col_selecionadas.loc[:, 'date_posted'] = df_col_selecionadas['date_posted'].str.split('T').str[0]
df_col_selecionadas.loc[:, 'ai_salary_min_value'] = df_col_selecionadas['ai_salary_min_value'].fillna(0).round(2)
df_col_selecionadas.loc[:, 'ai_salary_value'] = df_col_selecionadas['ai_salary_value'].fillna(0).round(2)
df_col_selecionadas.loc[:, 'ai_salary_max_value'] = df_col_selecionadas['ai_salary_max_value'].fillna(0).round(2)
df_col_selecionadas.loc[:, 'id'] = df_col_selecionadas['id'].astype('int64')
df_col_selecionadas = df_col_selecionadas.rename(columns={'locations': 'country'})

# EVITA ERRO DE PROGRAMAÇÃO CAUSADOS POR VALORES NaN AO INSERIR OS DADOS NA TABELA DO BANCO MYSQL 
df_col_selecionadas = df_col_selecionadas.where(
    pd.notnull(df_col_selecionadas),
    None
) 

df_col_selecionadas.head(3)
#df_col_selecionadas.info()

,id,date_posted,title,organization,country,ai_employment_type,source_type,seniority,ai_salary_currency,ai_salary_value,ai_salary_min_value,ai_salary_max_value,ai_salary_unit_text,ai_key_skills,ai_taxonomies_a,ai_education
0,2213012062,2026-06-18,Insulator,"Shambaugh & Son, L.P.",US,FULL_TIME,jobboard,Entry level,NaN,0.0,0.0,0.0,NaN,Insulation Installation,Trades,high school
1,2213011835,2026-06-18,Shipping and Receiving,Sika,US,FULL_TIME,jobboard,Entry level,NaN,0.0,0.0,0.0,NaN,Blueprint Reading,Construction,high school
2,2213012036,2026-06-18,Project Engineer I - Roadway,"CESO, INC.",US,FULL_TIME,jobboard,Entry level,USD,0.0,68415.0,122252.0,YEAR,Safety Procedures,Manufacturing,bachelor degree

In [12]:
import sys
import subprocess
subprocess.run([sys.executable, "-m", "pip", "install", "pymysql"], check=True)

CompletedProcess(args=['c:\\backup\\alan de souza-20260327T210536Z-3-001\\alan de souza\\projetos\\projeto portifolio\\python\\projeto_clonado\\etl_remotive_api\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'pymysql'], returncode=0)

In [ ]:
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL

load_dotenv()  
DB_HOST = os.getenv("DB_HOST")  
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_NAME = os.getenv("DB_NAME")
DB_CHARSET = os.getenv("DB_CHARSET")

engine = create_engine(URL.create(
    drivername="mysql+pymysql",
    username=DB_USER,
    password=DB_PASSWORD,  # passa a senha direto, sem precisar escapar
    host=DB_HOST,
    database=DB_NAME,
    query={"charset": DB_CHARSET}
))

In [14]:
df_col_selecionadas.columns

Index(['id', 'date_posted', 'title', 'organization', 'country',
       'ai_employment_type', 'source_type', 'seniority', 'ai_salary_currency',
       'ai_salary_value', 'ai_salary_min_value', 'ai_salary_max_value',
       'ai_salary_unit_text', 'ai_key_skills', 'ai_taxonomies_a',
       'ai_education'],
      dtype='str')

In [15]:
with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS remotive_tabela_empregos (
                      id BIGINT PRIMARY KEY,
                      date_posted DATE,
                      title VARCHAR(255),
                      organization VARCHAR(255),
                      country VARCHAR(255),
                      ai_employment_type VARCHAR(255),
                      source_type VARCHAR(255),
                      seniority VARCHAR(255),
                      ai_salary_currency VARCHAR(255),
                      ai_salary_value DECIMAL(15,2),
                      ai_salary_min_value DECIMAL(15,2),
                      ai_salary_max_value DECIMAL(15,2),
                      ai_salary_unit_text VARCHAR(255),
                      ai_key_skills VARCHAR(255),
                      ai_taxonomies_a VARCHAR(255),
                      ai_education VARCHAR(255)
        )
    """))

In [16]:
import numpy as np

def limpar_valor(v):
    if isinstance(v, float) and np.isnan(v):
        return None
    if isinstance(v, (np.int64, np.int32)):
        return int(v)
    if isinstance(v, (np.float64, np.float32)):
        return float(v)
    return v

with engine.begin() as conn:
    for i in range(len(df_col_selecionadas)):
        row = {col: limpar_valor(df_col_selecionadas[col][i]) for col in df_col_selecionadas.columns}
        conn.execute(text("""
            INSERT IGNORE INTO remotive_tabela_empregos (
                id, date_posted, title, organization, country,
                ai_employment_type, source_type, seniority,
                ai_salary_currency, ai_salary_value,
                ai_salary_min_value, ai_salary_max_value,
                ai_salary_unit_text, ai_key_skills,
                ai_taxonomies_a, ai_education
            ) VALUES (
                :id, :date_posted, :title, :organization, :country,
                :ai_employment_type, :source_type, :seniority,
                :ai_salary_currency, :ai_salary_value,
                :ai_salary_min_value, :ai_salary_max_value,
                :ai_salary_unit_text, :ai_key_skills,
                :ai_taxonomies_a, :ai_education
            )
        """), row)

In [19]:
import numpy as np

def limpar_valor(v):
    if isinstance(v, float) and np.isnan(v):
        return None
    if isinstance(v, (np.int64, np.int32)):
        return int(v)
    if isinstance(v, (np.float64, np.float32)):
        return float(v)
    return v

with engine.begin() as conn:
    for i in range(len(df_col_selecionadas)):
        row = {col: limpar_valor(df_col_selecionadas[col][i]) for col in df_col_selecionadas.columns}
        conn.execute(text("""
            INSERT IGNORE INTO remotive_tabela_empregos (
                id, date_posted, title, organization, country,
                ai_employment_type, source_type, seniority,
                ai_salary_currency, ai_salary_value,
                ai_salary_min_value, ai_salary_max_value,
                ai_salary_unit_text, ai_key_skills,
                ai_taxonomies_a, ai_education
            ) VALUES (
                :id, :date_posted, :title, :organization, :country,
                :ai_employment_type, :source_type, :seniority,
                :ai_salary_currency, :ai_salary_value,
                :ai_salary_min_value, :ai_salary_max_value,
                :ai_salary_unit_text, :ai_key_skills,
                :ai_taxonomies_a, :ai_education
            )
        """), row)